[package]
name = "rsafe"
version = "0.0.1"
authors = ["wrnice"]

[dependencies]
sodiumoxide = "*"
rustc-serialize = "*"
base64 ="*"
"url" ="*"
request ="*"


[lib]
name = "rsafe"
src = "src/lib.rs"

[[example]]
name = "example"
path = "examples/example.rs"